name: sams
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.3.0 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  #字体はここから
  assets:
    - assets/fonts/  
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
        - asset: assets/fonts/FjallaOne-Regular.ttf
