// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9BaNr7Pr9mb3KQIcrYMxpCO-n_sYLYFQ',
    appId: '1:82134360978:web:719bc957afab53a0f9974b',
    messagingSenderId: '82134360978',
    projectId: 'way2win-4964d',
    authDomain: 'way2win-4964d.firebaseapp.com',
    storageBucket: 'way2win-4964d.appspot.com',
    measurementId: 'G-0S4VPCJ5PH',
    databaseURL: 'https://way2win-4964d-default-rtdb.asia-southeast1.firebasedatabase.app', // 追加
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlKdiWOZy2J4W1D7ILck1lxzych7txu0',
    appId: '1:82134360978:android:374e966ee7d9a792f9974b',
    messagingSenderId: '82134360978',
    projectId: 'way2win-4964d',
    storageBucket: 'way2win-4964d.appspot.com',
    databaseURL: 'https://way2win-4964d-default-rtdb.asia-southeast1.firebasedatabase.app', // 追加
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArW6TEcTtxkLWHs-nETV4e1x-Dw3ysRlY',
    appId: '1:82134360978:ios:82fc7009306d8223f9974b',
    messagingSenderId: '82134360978',
    projectId: 'way2win-4964d',
    storageBucket: 'way2win-4964d.appspot.com',
    iosBundleId: 'com.example.sams',
    databaseURL: 'https://way2win-4964d-default-rtdb.asia-southeast1.firebasedatabase.app', // 追加
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArW6TEcTtxkLWHs-nETV4e1x-Dw3ysRlY',
    appId: '1:82134360978:ios:82fc7009306d8223f9974b',
    messagingSenderId: '82134360978',
    projectId: 'way2win-4964d',
    storageBucket: 'way2win-4964d.appspot.com',
    iosBundleId: 'com.example.sams',
    databaseURL: 'https://way2win-4964d-default-rtdb.asia-southeast1.firebasedatabase.app', // 追加
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9BaNr7Pr9mb3KQIcrYMxpCO-n_sYLYFQ',
    appId: '1:82134360978:web:8c2585ecff14a497f9974b',
    messagingSenderId: '82134360978',
    projectId: 'way2win-4964d',
    authDomain: 'way2win-4964d.firebaseapp.com',
    storageBucket: 'way2win-4964d.appspot.com',
    measurementId: 'G-X5WR5G8J1H',
    databaseURL: 'https://way2win-4964d-default-rtdb.asia-southeast1.firebasedatabase.app', // 追加
  );
}
